### ISSUE TITLE
hey look at this

### ISSUE THREAD

**Issue by amonks** [theuprising/snackpack#12]
hey @rongierlach and @kilokeith 

I have three libraries going that I think represent a pretty cool direction to head for library code.

- [crumbles](https://github.com/theuprising/crumbles), which y'all know about
- [snackstack](https://github.com/theuprising/snackstack), which provides some scripts that the other two libraries use in package.json.scripts
- [snackcli](https://github.com/theuprising/snackcli), which provides some utilities for making cli tools

## things you'll notice

- if you run `npm run test` in any of them it runs `snackstack test`, which does three things:
  - run lint
  - run flow type checking on files with a `// @flow` annotation
    - if you run `npm run install:types`, it downloads type definitions for required node modules if they exist, or generates usable stubs if they don't.
  - run any jest tests (`**/*.test.js` or `__tests__/*.js`)
- if you run `npm run docs` in any of them, it runs `snackstack docs`, which builds a docs page.

## todo

I'm sure I haven't documented anything enough, and you'll have further questions. Commenting here is a good way to ask.

check them out. read the code. tell me what you think. is this a good pattern to adopt? does `snackstack` make sense as a thing? let's talk about it.

If you're on board, and you want to jump into some code, here are some things that need to happen:

- config: how should it work?
  - I wrote down some initial thoughts about the problem under *config injection* [here](https://github.com/theuprising/snackpack/issues/10#issuecomment-258468544)
  - this is probably our hardest problem.
- crumbles
  - [ ] needs more tests
  - [ ] needs more jsdoc annotations
- snackstack
  - [ ] needs more tests
  - [ ] needs more jsdoc annotations
  - [ ] figure out whether it makes sense to use a utility like this for client projects
- snackcli
  - [ ] needs more tests
  - [ ] needs more jsdoc annotations
- snackpack
  - [ ] needs to move into this new structure
  - [ ] the other libraries need to use it
    - right now, you'll notice that each library has a webpack.config file that declares a bunch of functions, and then exports their composition. the way I see it, snackpack should be a library that exports those functions, and the individual repos should require them and export their composition. That way, it's _super clear_ how to add your own stuff to the config when needed. 
- [ ] we need a better project management system for this. this todo list ain't cuttin it.
  - options: 
    - github issues
    - make a pivotal board
    - ???
  - I don't have strong opinions about this. If someone felt like setting something up, I'd be grateful. If not, I'll figure something out eventually.
- actual project code
  - this is all well and good for libraries, but we oughta have a conversation/consensus about which parts of infrastructure scale to client projects. jsdoc and jest probably don't. flow annotations might. snackstack scripts maybe do.
- [ ] extract a library template, probably from crumbles

**Comment by rongierlach** [comment]
I can endeavor to get some better test coverage and more comprehensive docs going for crumbles.

**Comment by amonks** [comment]
rad
